# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d61f81c3ece48603724a7193a4109ef9172258ce749f4684fbfbe495dc505a79713394096fa5f10d7181149408cce386003bca80f33116e5c723a1ee6b3de50

test:
  secret_key_base: ba0406b8d14066163ded01b46592afd5bc610eef55d051c9861bfbc174b4add18942856430942b1821f9cc0000ef611dbb011c7e29330532eb4d7b2594610ea1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
